# version: '3.7'

services:
  ##################################
  # Backing Services 
  ##################################
  # MongoDB backing service
  mongodb:
    image: mongo:7.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "-u", "root", "-p", "example", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 3s
      timeout: 6s
      retries: 15
    profiles:
      - all
      - mongodb
      - mongoonly
      - kafka
      - curriculum
      - encounter
      - partner
      - person
      - search
      - topic
      - curriculum-api
      - encounter-api
      - partner-api
      - person-api
      - search-api
      - topic-api
      - msm

  ##################################
  # Elasticsearch backing service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "xpack.security.enabled=false"
      - "action.destructive_requires_name=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    profiles:
      - all
      - kafka
      - elasticsearch
      - elasticonly
      - search-api
      - search

  ##################################
  # Kibana for Elasticsearch service
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: c69548d9027afcf4d55146b1d425a9f4c69548d9027afcf4d55146b1d425a9f4
    profiles:
      - all
      - kafka
      - elasticsearch
      - elasticonly
      - search-api
      - search

  ##################################
  # Zookeeper manager for Kafka cluster
  zookeeper:
    image: zookeeper:3.9.2
    ports:
      - "2181:2181"
    profiles:
      - all
      - kafka
      - search-api
      - search

  ##################################
  # Kafka event bus
  kafka:
    image: confluentinc/cp-kafka:7.3.0  
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:19092
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    depends_on:
      - zookeeper
    profiles:
      - all
      - kafka
      - search-api
      - search

  ##################################
  # Kafka Connector
  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.3.10
    ports:
      - "9093:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:19092
      CONNECT_REST_ADVERTISED_HOST_NAME: localhost
      CONNECT_GROUP_ID: "mongo-elastic-sync"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PLUGIN_PATH: "/usr/share/java"
    depends_on:
      kafka:
        condition: service_started
      mentorhub-msm:
        condition: service_completed_successfully
      mentorhub-elasticsearch:
        condition: service_completed_successfully
    profiles:
      - all
      - kafka
      - search-api
      - search

  ##################################
  # Backing Service Configuration Utilities
  ##################################
  # Mongo Schema Manager utility - for testing of mentorhub-msm
  # Not a part of the deployment code
  msm:
    image: ghcr.io/agile-learning-institute/msm:latest
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - CONNECTION_STRING=mongodb://root:example@mongodb:27017
      - LOAD_TEST_DATA=true
      - DB_NAME=mentorHub
    volumes:
      - ${CONFIGURATIONS}:/opt/mongoSchemaManager/configurations
    profiles: 
      - msm

  ##################################
  # Initilize MongoDB and load test data
  mentorhub-msm:
    image: ghcr.io/agile-learning-institute/mentorhub-msm:latest
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - CONNECTION_STRING=mongodb://root:example@mongodb:27017
      - LOAD_TEST_DATA=true
      - DB_NAME=mentorHub
    profiles:
      - all
      - kafka
      - mongodb
      - curriculum
      - encounter
      - partner
      - person
      - search
      - topic
      - curriculum-api
      - encounter-api
      - partner-api
      - person-api
      - search-api
      - topic-api
      - msm

  ##################################
  # Initilize Elasticsearch and load test data
  mentorhub-elasticsearch:
    image: ghcr.io/agile-learning-institute/mentorhub-elasticsearch:latest
    environment:
      CLIENT_OPTIONS: '{"node":"http://elasticsearch:9200"}'
      MONGO_CONNECTION_STRING: mongodb://root:example@mongodb:27017
      LOAD_TEST_DATA: true
    depends_on:
      mentorhub-msm:
        condition: service_completed_successfully
      elasticsearch:
        condition: service_healthy
    profiles:
      - all
      - kafka
      - elasticsearch
      - search-api
      - search

  ##################################
  # Initilize Kafka and configure Kafka Connectors
  mentorhub-kafka:
    image: ghcr.io/agile-learning-institute/mentorhub-curriculum-api:latest
    restart: no
    environment:
      ELASTIC_CONNECTION_STRING: elasticsearch://
      KAFKA_CONNECT_URL: kafka-connect://
      MONGODB_URI: mongodb://root:example@mongodb:27017/?tls=false&directConnection=true
    depends_on:
      mentorhub-msm:
        condition: service_completed_successfully
      mentorhub-elasticsearch:
        condition: service_completed_successfully
      kafka-connect:
        condition: service_started
    profiles:
      - all
      - kafka

  ##################################
  # API's 
  ##################################
  mentorhub-curriculum-api:
    image: ghcr.io/agile-learning-institute/mentorhub-curriculum-api:latest
    restart: no
    ports:
      - 8088:8088
    environment:
      CONNECTION_STRING: mongodb://root:example@mongodb:27017/?tls=false&directConnection=true
    depends_on:
      mentorhub-msm:
        condition: service_completed_successfully
    profiles:
      - all
      - curriculum
      - curriculum-api

  mentorhub-encounter-api:
    image: ghcr.io/agile-learning-institute/mentorhub-encounter-api:latest
    restart: no
    ports:
      - 8090:8090
    environment:
      CONNECTION_STRING: mongodb://root:example@mongodb:27017/?tls=false&directConnection=true
    depends_on:
      mentorhub-msm:
        condition: service_completed_successfully
    profiles:
      - all
      - encounter
      - encounter-api

  mentorhub-partner-api:
    image: ghcr.io/agile-learning-institute/mentorhub-partner-api:latest
    restart: no
    ports:
      - 8084:8084
    environment:
      CONNECTION_STRING: mongodb://root:example@mongodb:27017/?tls=false&directConnection=true
    depends_on:
      mentorhub-msm:
        condition: service_completed_successfully
    profiles:
      - all
      - partner
      - partner-api

  mentorhub-person-api:
    image: ghcr.io/agile-learning-institute/mentorhub-person-api:latest
    restart: no
    ports:
      - 8082:8082
    environment:
      CONNECTION_STRING: mongodb://root:example@mongodb:27017/?tls=false&directConnection=true
    depends_on:
      mentorhub-msm:
        condition: service_completed_successfully
    profiles:
      - all
      - person
      - person-api

  mentorhub-search-api:
    image: ghcr.io/agile-learning-institute/mentorhub-search-api:latest
    restart: no
    ports:
      - 8081:8081
    environment:
      HOST: mentorhub-searchdb
    depends_on:
      mentorhub-searchinit:
        condition: service_completed_successfully
    profiles:
      - all
      - search
      - search-api

  mentorhub-topic-api:
    image: ghcr.io/agile-learning-institute/mentorhub-topic-api:latest
    ports:
      - 8086:8086
    environment:
      CONNECTION_STRING: mongodb://root:example@mongodb:27017/?tls=false&directConnection=true
    depends_on:
      mentorhub-msm:
        condition: service_completed_successfully
    profiles:
      - all
      - topic
      - topic-api

  ##################################
  # SPA's start here
  ##################################
  mentorhub-curriculum-ui:
    image: ghcr.io/agile-learning-institute/mentorhub-curriculum-ui:latest
    restart: no
    environment:
      API_HOST: mentorhub-curriculum-api
      API_PORT: 8088
    ports:
      - 8089:80
    depends_on:
      - mentorhub-curriculum-api
    profiles:
      - all
      - curriculum

  mentorhub-encounter-ui:
    image: ghcr.io/agile-learning-institute/mentorhub-encounter-ui:latest
    restart: no
    environment:
      API_HOST: mentorhub-encounter-api
      API_PORT: 8090
    ports:
      - 8091:80
    depends_on:
      - mentorhub-encounter-api
    profiles:
      - all
      - encounter

  mentorhub-partner-ui:
    image: ghcr.io/agile-learning-institute/mentorhub-partner-ui:latest
    restart: no
    environment:
      API_HOST: mentorhub-partner-api
      API_PORT: 8084
    ports:
      - 8085:80
    depends_on:
      - mentorhub-partner-api
    profiles:
      - all
      - partner

  mentorhub-person-ui:
    image: ghcr.io/agile-learning-institute/mentorhub-person-ui:latest
    restart: no
    environment:
      API_HOST: mentorhub-person-api
      API_PORT: 8082
    ports:
      - 8083:80
    depends_on:
      - mentorhub-person-api
    profiles:
      - all
      - person

  mentorhub-search-ui:
    image: ghcr.io/agile-learning-institute/mentorhub-search-ui:latest
    restart: no
    environment:
      API_HOST: mentorhub-search-api
      API_PORT: 8081
    ports:
      - 80:80
    depends_on:
      - mentorhub-search-api
    profiles:
      - all
      - search

  mentorhub-topic-ui:
    image: ghcr.io/agile-learning-institute/mentorhub-topic-ui:latest
    restart: no
    environment:
      API_HOST: mentorhub-topic-api
      API_PORT: 8086
    ports:
      - 8087:80
    depends_on:
      - mentorhub-topic-api
    profiles:
      - all
      - topic
