version: '3.1'

services:
  mentorhub-mongodb:
    image: mongo:7.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "-u", "root", "-p", "example", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 3s
      timeout: 2s
      retries: 15
    profiles:
      - mongoonly
      - mongodb
      - curriculum
      - encounter
      - partner
      - person
      - topic
      - curriculum-api
      - encounter-api
      - partner-api
      - person-api
      - topic-api
      - msm

  mentorhub-searchdb:
    image: opensearchproject/opensearch:2.12.0
    environment:
      discovery.type: single-node
      cluster-name: mentorHub
      plugins.security.disabled: true
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 55CKoK;9|'g{8i<4|Gny6pUX
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
    profiles:
      - opensearchonly
      - search
      - search-db
      - search-api

  msm:
    image: ghcr.io/agile-learning-institute/msm:latest
    depends_on:
      mentorhub-mongodb:
        condition: service_healthy
    environment:
      - CONNECTION_STRING=mongodb://root:example@mentorhub-mongodb:27017
      - LOAD_TEST_DATA=true
      - DB_NAME=mentorHub
    volumes:
      - ${CONFIGURATIONS}:/opt/mongoSchemaManager/configurations
    profiles: 
      - msm

  mentorhub-mongomsm:
    image: ghcr.io/agile-learning-institute/mentorhub-msm:latest
    depends_on:
      mentorhub-mongodb:
        condition: service_healthy
    environment:
      - CONNECTION_STRING=mongodb://root:example@mentorhub-mongodb:27017
      - LOAD_TEST_DATA=true
      - DB_NAME=mentorHub
    profiles:
      - mongodb
      - curriculum
      - encounter
      - partner
      - person
      - topic
      - curriculum-api
      - encounter-api
      - partner-api
      - person-api
      - topic-api

  mentorhub-searchinit:
    image: ghcr.io/agile-learning-institute/mentorhub-search-searchinit:latest
    depends_on:
      mentorhub-searchdb:
        condition: service_healthy
    environment:
      HOST: mentorhub-searchdb
    profiles:
      - search
      - search-db
      - search-api

  mentorhub-curriculum-api:
    image: ghcr.io/agile-learning-institute/mentorhub-curriculum-api:latest
    restart: always
    ports:
      - 8088:8088
    environment:
      CONNECTION_STRING: mongodb://root:example@mentorhub-mongodb:27017/?tls=false&directConnection=true
    depends_on:
      mentorhub-mongomsm:
        condition: service_completed_successfully
    profiles:
      - curriculum
      - curriculum-api

  mentorhub-encounter-api:
    image: ghcr.io/agile-learning-institute/mentorhub-encounter-api:latest
    restart: always
    ports:
      - 8090:8090
    environment:
      CONNECTION_STRING: mongodb://root:example@mentorhub-mongodb:27017/?tls=false&directConnection=true
    depends_on:
      mentorhub-mongomsm:
        condition: service_completed_successfully
    profiles:
      - encounter
      - encounter-api

  mentorhub-partner-api:
    image: ghcr.io/agile-learning-institute/mentorhub-partner-api:latest
    restart: always
    ports:
      - 8084:8084
    environment:
      CONNECTION_STRING: mongodb://root:example@mentorhub-mongodb:27017/?tls=false&directConnection=true
    depends_on:
      mentorhub-mongomsm:
        condition: service_completed_successfully
    profiles:
      - partner
      - partner-api

  mentorhub-person-api:
    image: ghcr.io/agile-learning-institute/mentorhub-person-api:latest
    restart: always
    ports:
      - 8082:8082
    environment:
      CONNECTION_STRING: mongodb://root:example@mentorhub-mongodb:27017/?tls=false&directConnection=true
    depends_on:
      mentorhub-mongomsm:
        condition: service_completed_successfully
    profiles:
      - person
      - person-api

  mentorhub-search-api:
    image: ghcr.io/agile-learning-institute/mentorhub-search-api:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      HOST: mentorhub-searchdb
    depends_on:
      mentorhub-searchinit:
        condition: service_completed_successfully
    profiles:
      - search
      - search-api

  mentorhub-topic-api:
    image: ghcr.io/agile-learning-institute/mentorhub-topic-api:latest
    ports:
      - 8086:8086
    environment:
      CONNECTION_STRING: mongodb://root:example@mentorhub-mongodb:27017/?tls=false&directConnection=true
    depends_on:
      mentorhub-mongomsm:
        condition: service_completed_successfully
    profiles:
      - topic
      - topic-api

  mentorhub-curriculum-ui:
    image: ghcr.io/agile-learning-institute/mentorhub-curriculum-ui:latest
    restart: always
    environment:
      API_HOST: mentorhub-curriculum-api
      API_PORT: 8088
    ports:
      - 8089:80
    depends_on:
      - mentorhub-curriculum-api
    profiles:
      - curriculum

  mentorhub-encounter-ui:
    image: ghcr.io/agile-learning-institute/mentorhub-encounter-ui:latest
    restart: always
    environment:
      API_HOST: mentorhub-encounter-api
      API_PORT: 8090
    ports:
      - 8091:80
    depends_on:
      - mentorhub-encounter-api
    profiles:
      - encounter

  mentorhub-partner-ui:
    image: ghcr.io/agile-learning-institute/mentorhub-partner-ui:latest
    restart: always
    environment:
      API_HOST: mentorhub-partner-api
      API_PORT: 8084
    ports:
      - 8085:80
    depends_on:
      - mentorhub-partner-api
    profiles:
      - partner

  mentorhub-person-ui:
    image: ghcr.io/agile-learning-institute/mentorhub-person-ui:latest
    restart: always
    environment:
      API_HOST: mentorhub-person-api
      API_PORT: 8082
    ports:
      - 8083:80
    depends_on:
      - mentorhub-person-api
    profiles:
      - person

  mentorhub-search-ui:
    image: ghcr.io/agile-learning-institute/mentorhub-search-ui:latest
    restart: always
    environment:
      API_HOST: mentorhub-search-api
      API_PORT: 8081
    ports:
      - 80:80
    depends_on:
      - mentorhub-search-api
    profiles:
      - search

  mentorhub-topic-ui:
    image: ghcr.io/agile-learning-institute/mentorhub-person-ui:latest
    restart: always
    environment:
      API_HOST: mentorhub-topic-api
      API_PORT: 8086
    ports:
      - 8087:80
    depends_on:
      - mentorhub-topic-api
    profiles:
      - topic

