version: '3.1'

services:
  mentorhub-mongodb:
    image: mongo:7.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "-u", "root", "-p", "example", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 15s
      timeout: 10s
      retries: 5
    profiles:
      - mongoonly
      - mongodb
      - person
      - person-api
      - topic-api
      - topic

  mentorhub-searchdb:
    image: opensearchproject/opensearch:2.12.0
    environment:
      discovery.type: single-node
      cluster-name: mentorHub
      plugins.security.disabled: true
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 55CKoK;9|'g{8i<4|Gny6pUX
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
    profiles:
      - opensearchonly
      - search
      - search-db
      - search-api

  mentorhub-mongosh:
    image: ghcr.io/agile-learning-institute/mentorhub-mongosh:latest
    depends_on:
      mentorhub-mongodb:
        condition: service_healthy
    environment:
      - USER=root
      - PASSWORD=example
    entrypoint: ["/mongosh/entrypoint.sh"]
    profiles:
      - mongodb
      - person
      - person-api
      - topic-api
      - topic

  mentorhub-searchinit:
    image: ghcr.io/agile-learning-institute/mentorhub-search-searchinit:latest
    depends_on:
      mentorhub-searchdb:
        condition: service_healthy
    environment:
      HOST: mentorhub-searchdb
    profiles:
      - search
      - search-db
      - search-api

  mentorhub-person-api:
    image: ghcr.io/agile-learning-institute/mentorhub-person-api:latest
    restart: always
    ports:
      - 8082:8082
    environment:
      CONNECTION_STRING: mongodb://root:example@mentorhub-mongodb:27017/?tls=false&directConnection=true
    depends_on:
      mentorhub-mongosh:
        condition: service_completed_successfully
    profiles:
      - person
      - person-api

  mentorhub-topic-ui:
    image: ghcr.io/agile-learning-institute/mentorhub-person-ui:latest
    restart: always
    environment:
      API_HOST: mentorhub-topic-api
      API_PORT: 8082
    ports:
      - 8083:80
    depends_on:
      - mentorhub-topic-api
    profiles:
      - topic

  mentorhub-person-ui:
    image: ghcr.io/agile-learning-institute/mentorhub-person-ui:latest
    restart: always
    environment:
      API_HOST: mentorhub-person-api
      API_PORT: 8082
    ports:
      - 8083:80
    depends_on:
      - mentorhub-person-api
    profiles:
      - person

  mentorhub-search-api:
    image: ghcr.io/agile-learning-institute/mentorhub-search-api:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      HOST: mentorhub-searchdb
    depends_on:
      mentorhub-searchinit:
        condition: service_completed_successfully
    profiles:
      - search
      - search-api

  mentorhub-topic-api:
    image: ghcr.io/agile-learning-institute/mentorhub-topic-api:latest
    ports:
      - 8086:8086
    environment:
      CONNECTION_STRING: mongodb://root:example@mentorhub-mongodb:27017/?tls=false&directConnection=true
    depends_on:
      mentorhub-mongosh:
        condition: service_completed_successfully
    profiles:
      - topic
      - topic-api
